services:
    server:
        container_name: "${APP_SLUG}-server"
        image: ghcr.io/europlan-spa/${APP_SLUG}:master
        restart: unless-stopped
        labels:
            com.centurylinklabs.watchtower.enable: true
            # caddy: www.domain.it
            # caddy.reverse_proxy: "{{upstreams 80}}"
            # caddy_1: domain.it
            # caddy_1.redir: "https://www.domain.it{uri} permanent"
        volumes:
            - '/var/docker/${APP_SLUG}/uploads:/var/www/html/public/uploads'
            - '/var/backup/${APP_SLUG}:/var/www/html/storage/app/laravel-backup'
        # ports:
        #     - '${APP_PORT:-80}:80'
        environment:
          APP_ENV: 'production'
          APP_DEBUG: 'false'
        env_file:
            - stack.env
        networks:
            - sail
            # - public
        depends_on:
            - mysql
    mysql:
        container_name: "${APP_SLUG}-db"
        image: 'mysql/mysql-server'
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            TZ: Europe/Rome
        env_file:
            - stack.env
        volumes:
            - '/var/docker/${APP_SLUG}/mysql:/var/lib/mysql'
        networks:
            - sail
            - phpmyadmin
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
networks:
    phpmyadmin:
        external: true
    # Used with caddy
    # public:
    #     external: true
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
